apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
  labels:
    team: edu-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
        team: edu-app
    spec:
      containers:
        - name: payment-service
          image: educationalapp-payment-service:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
  labels:
    team: edu-app
spec:
  selector:
    app: payment-service
  ports:
    - port: 3003
      targetPort: 3003
